### ISSUE TITLE
Not currently displaying images

### ISSUE THREAD

**Issue by danielb2** [fooblahblah/craigslistpreview#1]
Here's an example URL: http://sfbay.craigslist.org/search/?areaID=1&subAreaID=&query=motorcycle&catAbb=sss

The extension is enabled, but it's not behaving like it used to.

**Comment by fooblahblah** [comment]
Thanks for the bug report and, most importantly, the link!  :)  I'll take a look when I have a chance.

**Comment by phel0049** [comment]
I am having the same issue, extension isn't working at all since Friday at least.  On ANY Craigslist page I visit, but here is the one I visit the most often if that is of help to you: http://minneapolis.craigslist.org/hnp/zip/  I have Google Chrome version 21.0.1180.60 m.  Maybe something happenned in a recent Chrome update that broke the extension? I noticed at the same time the Craigslist icon (.ico) image stopped appearing in the address bar.
